name: build & test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on:
      group: k23a

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -Wno-dev

      - name: Build the test binaries
        run: |
          cmake --build build --target \
            unit_tests \
            robinhood_tests \
            cuckoo_tests \
            hopscotch_tests \
            valuet_tests \
            -j$(nproc)

      - name: Run tests
        run: |
          ./build/unit_tests
          ./build/robinhood_tests
          ./build/cuckoo_tests
          ./build/hopscotch_tests
          ./build/valuet_tests
          

      - name: Build fast executable
        run: |
          cmake --build build --target fast -j$(nproc)

