name: build & test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on:
      group: k23a

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -Wno-dev

      - name: Build fast + tests
        run: |
          cmake --build build \
            --target fast \
            -j$(nproc)

      - name: Run tests (CTest)
        run: |
          cd build
          ctest --output-on-failure


